# Use postgres/example user/password credentials
version: '3.9'

services:

  database:
    image: postgres
    container_name: codarme_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin - POSTGRES_PASSWORD=admin - POSTGRES_DB=tweet

    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
